### ISSUE TITLE
Can't make sense of the following error

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#1]
PG::ConnectionBad at /
could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb in mon_synchronize
      yield
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb in mon_synchronize
      yield
/Users/FutureChild/src/Crazy_Restaurant/views/index.erb in block in singleton class
    <% @inventory_items.each do |inventory_item| %>
/Users/FutureChild/src/Crazy_Restaurant/controllers/welcome_controller.rb in block in class:WelcomeController
    erb :index
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb in service
      si.service(req, res)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb in run
          server.service(req, res)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb in block in start_thread
          block ? block.call(sock) : run(sock)
GET
No GET data.
POST
No POST data.
COOKIES
No cookie data.

**Comment by amadden80** [comment]
The error says `Is the server running locally`.  Is postgres running on your machine?

**Comment by eerlikh** [comment]
no because I just updated it and had to restart it, that I why it didn't make sense, psql is always running

**Comment by eerlikh** [comment]
(restart my comp because of update)
