### ISSUE TITLE
Need to solve my final crud app issue - routing my orders table

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#10]
So Yesterday with Andrews help I managed to get inventory items and parties to be editable. Now I have to get orders to work. But I keep getting an error due to what I imagine to be a syntax problem. 

I still have trouble accessing ruby hashes and arrays due to lack of practice. 

I'm working on this issue now, would appreciate help whenever it is available. 

User Story

As a wait staff, I want to be able to edit my order, so that I can make changes in case i mess up.

Context

i can't figure out the key necessary to access the orders data.

When I'm trying to do this thing... 
I have tried...
What triggers the bug...
Error Message

NoMethodError at /orders/41/edit
undefined method `table_number' for 14:Fixnum
file: edit.erb location: block in singleton class line: 6
BACKTRACE
(expand)
JUMP TO: GET POST COOKIES ENV
/Users/FutureChild/src/Crazy_Restaurant/views/orders/edit.erb in block in singleton class
  <input type="text" name="order[party_id]" value="<%= @order.party_id.table_number %>">
/Users/FutureChild/src/Crazy_Restaurant/controllers/orders_controller.rb in block in class:OrdersController
    erb :'orders/edit'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb in service
      si.service(req, res)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb in run
          server.service(req, res)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb in block in start_thread
          block ? block.call(sock) : run(sock)

**Comment by eerlikh** [comment]
Also need help getting the total price ><

**Comment by eerlikh** [comment]
I'm going to need help in person

**Comment by eerlikh** [comment]
Once I get this help I can implement everything else on my own

**Comment by amadden80** [comment]
We see your issue and will address it in order.

**Comment by eerlikh** [comment]
thank you

**Comment by amadden80** [comment]
_in person_
