### ISSUE TITLE
remove button not working for my parties but working for my inventory items, why god?

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#3]
getting this error
Try this:
# in controllers/application_controller.rb

class PartiesController
  delete '/2' do
    "Hello World"
  end
end

**Comment by eerlikh** [comment]
however my inventory items doesn't seem to have a delete method, why does my inventory item remove work but not my party remove????

**Comment by rapala61** [comment]
Try changing the route from  '/2' to '/:id', let me know how it goes:

``` ruby

delete '/:id' do
 # Delete instance here
end
```

**Comment by eerlikh** [comment]
ok one sec

**Comment by eerlikh** [comment]
rapa, still doesn't answer the question of why my inventory item remove works???

**Comment by eerlikh** [comment]
in my understanding if one doesn't work the other one shouldn't work either

**Comment by rapala61** [comment]
@eerlikh I cant see your updated code, commit and push.

**Comment by eerlikh** [comment]
good idea! one sec

Try this:

# in controllers/application_controller.rb

class PartiesController
  delete '/2' do
    "Hello World"
  end
end

also error wasn't fixed ... seems like a deeper routing issue, give me 3 minutes to commit and push

**Comment by eerlikh** [comment]
Updated

**Comment by eerlikh** [comment]
grabbing lunch

**Comment by eerlikh** [comment]
back

**Comment by eerlikh** [comment]
found any problems in the code yet?

**Comment by eerlikh** [comment]
can someone please explain to me how destroy works? I think I'm routing it incorrectly

**Comment by eerlikh** [comment]
nvm
 it was working the whole time lol, I don't know why I had an error earlier... weird.

**Comment by eerlikh** [comment]
lol, I forgot to bundle exec ... after all the times andrew hurt himself on the chair
