### ISSUE TITLE
For some reason my order is not showing up

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#4]
I get the following error 

/Users/FutureChild/src/Crazy_Restaurant/views/orders/index.erb in block (2 levels) in singleton class
      <%= order.inventory_item.name %> - <%= order.party.table_number %>
/Users/FutureChild/src/Crazy_Restaurant/views/orders/index.erb in block in singleton class
  <% @orders.each do |order| %>
/Users/FutureChild/src/Crazy_Restaurant/controllers/orders_controller.rb in block in class:OrdersController
    erb :'orders/index'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb in service
      si.service(req, res)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb in run
          server.service(req, res)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb in block in start_thread
          block ? block.call(sock) : r

seem to have routed everything correctly

**Comment by eerlikh** [comment]
for once I did everything right ><

welp, I officially hit a wall, doing some css till I get help.

**Comment by rapala61** [comment]
Start a new issue with the description in detail of what you need help with.

**Comment by eerlikh** [comment]
alright, I'll add more details
