### ISSUE TITLE
Although I routed my orders, they are not being recognized

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#5]
when I go to the url http://localhost:9292/orders

I get the following error 

NoMethodError at /orders
undefined method `name' for nil:NilClass

/Users/FutureChild/src/Crazy_Restaurant/views/orders/index.erb in block (2 levels) in singleton class
      <%= order.inventory_item.name %> - <%= order.party.table_number %>
/Users/FutureChild/src/Crazy_Restaurant/views/orders/index.erb in block in singleton class
  <% @orders.each do |order| %>
/Users/FutureChild/src/Crazy_Restaurant/controllers/orders_controller.rb in block in class:OrdersController
    erb :'orders/index'

it's saying  order.inventory_item.name is undefined  but I very clearly defined it

**Comment by rapala61** [comment]
commit and push your latest changes

**Comment by eerlikh** [comment]
ok, done

**Comment by eerlikh** [comment]
find anything weird?

**Comment by eerlikh** [comment]
because for the life of me I see nothing wrong ><

**Comment by rapala61** [comment]
I deployed your repo in my laptop, orders display nicely on my browser: 
![screen shot 2015-08-26 at 2 25 59 pm](https://cloud.githubusercontent.com/assets/863301/9502291/6bb4e122-4bfe-11e5-8767-e9e730d37717.png)

**Comment by rapala61** [comment]
Are you sure you have bundled and all your migrations were ran correctly?

**Comment by eerlikh** [comment]
damn I don't know, I'll check

**Comment by eerlikh** [comment]
yeah, I bundled everything ,racked up and cleared my cache and stuff. I'm going to bring emily and andrew in on this issue, since you just went to meet up with someone, but thank you for verifying that the problem is my machine and not the code, helps out a lot.

**Comment by eerlikh** [comment]
So I need someone to take a quick look at my machine and tell me what's wrong and why rafa was able to use the code I couldn't.

**Comment by eerlikh** [comment]
<img width="1114" alt="screen shot 2015-08-26 at 2 33 59 pm" src="https://cloud.githubusercontent.com/assets/8581776/9502490/9f37bc76-4bff-11e5-95be-a2eb67ea6f33.png">

**Comment by eerlikh** [comment]
anyone??

**Comment by eerlikh** [comment]
Oh wow, sophie sovled it, apparently I had a blank object in my table... I don't see how it was messing it up but whatever.
