### ISSUE TITLE
I need help concatenating my inventory items into a string to put into a table

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#6]
need an instructor to walk me through this because my app doesn't work at the moment because I select multiple items and they break the table.

**Comment by amadden80** [comment]
Use the github format we've discussed in class for support.

---

###Issue Format:

```
User Story

As a _____, I want to be able to _____, so that I can _____.

Context

When I'm trying to do this thing...
I have tried...
What triggers the bug...
Error Message

//Paste the error message
```
