### ISSUE TITLE
I need help concatenating my inventory items into a string to put into my Orders table 

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#7]
User Story

As a wait staff I want to be able to click on all the check boxes I need to place a proper order instantly, I want to do that so that I can move on to the next customer quickly.

Context

When I'm trying to...

Make an Order, I select multiple inventory food items, my orders table is unable to accommodate my selection.

I think the solution involves taking all the inventory items and putting them in a string into the orders table. I'm having trouble doing that. 

Error Message
order.party or order.inventory_items remain undefined for some reason. 

//Paste the error message

**Comment by amadden80** [comment]
_in person_

**Comment by amadden80** [comment]
_Working on implemented_

**Comment by eerlikh** [comment]
I'm just going to reopen this issue until I've completely solved it.

**Comment by eerlikh** [comment]
I'd like to get the solution before the end of the day if possible, I'm currently looking up the syntax and stuff now.
