### ISSUE TITLE
Can't seem to get my edit to work

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#8]
User Story

As a wait staff, I want to be able to edit all items, so that I can increase the wait staff's work efficiency.

I basically setup all the routes but it's telling me it can't find the route.

I tried to make sure all my syntax is correct but I can't find the problem in my logic.

Error Message - 

Sinatra doesn’t know this ditty.

Try this:
# in controllers/application_controller.rb

class OrdersController
  get '/edit' do
    "Hello World"
  end
end

**Comment by eerlikh** [comment]
Also need help creating a price column for my inventory items table

**Comment by emilylordahl** [comment]
Are you trying to edit all food items? Your error is coming from the application controller. If you want to edit food items, you should be working in your food items controller.

**Comment by eerlikh** [comment]
class OrdersController < ApplicationController

  # '/orders'
  get '/' do
    # binding.pry
    @orders = Order.all
    erb :'orders/index'
  end

  # '/orders/new'
  get '/new' do
    @inventory_items = InventoryItem.all
    @parties = Party.all
    erb :'orders/new'
  end

  # '/orders'
  post '/' do
    # binding.pry
    # {"order"=>{"party_id"=>"7"}, "inventory_items"=>["10", "11"]}

```
party_id = params['party_id']
inventory_items =  params['inventory_items']

inventory_items.each do |inventory_item|
  Order.create({
    party_id: party_id,
    inventory_item_id: inventory_item
    })
end
```

  # Order.create(params[:order])
  redirect '/'
  end

  # '/orders/:id/edit'
  get ':id/edit' do
    @order = Order.find(param[:id])
    erb :'orders/edit'
  end
  # '/orders/:id'
  put ':id' do
    order = Order.find(param[:id])
    order.update(params[:cheese])
    redirect "/orders/#{order.id}"
  end

  delete '/:id' do
    # Delete instance here
    Order.delete(params[:id])
    redirect '/'
  end

end

**Comment by eerlikh** [comment]
my edit. erb

<h2> Edit Order </h2>

<form action="/orders/<%= order.id %>" method="post">
  <input type="hidden" name="_method" value="put">
  <input type="text" name="order[name]" value="<%= @order.name %>">
  <input type="submit" value="Update Order">
</form>

**Comment by eerlikh** [comment]
<h2> Edit Order </h2>

<form action="/orders/<%= order.id %>" method="post">
  <input type="hidden" name="_method" value="put">
  <input type="text" name="order[name]" value="<%= @order.name %>">
  <input type="submit" value="Update Order">
</form>

**Comment by emilylordahl** [comment]
Because you are working within the `OrdersController`, all of your routes do not need to include `/order`. So the index route should be:

``` rb
get '/' do
   @orders = Order.all
   erb :'orders/index'
end
```

and that pattern should continue for all routes within your controller.

**Comment by eerlikh** [comment]
already had an index route.   

get '/' do
    @orders = Order.all
    erb :'orders/index'
  end

**Comment by eerlikh** [comment]
Does anyone have a moment to help me debug??

**Comment by eerlikh** [comment]
all my logic is in place I just need help finding my mistake, I'm really bad at debugging.

**Comment by emilylordahl** [comment]
Want to come out to the tables?

**Comment by amadden80** [comment]
_in person_
