### ISSUE TITLE
Edit issue continued 

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/Crazy_Restaurant#9]
I finally managed to display my views but when I click to update my associations are all messed up. 

User Story

As a wait staff, I want to be able to edit all items, so that I can increase the wait staff's work efficiency.

I basically setup all the routes but it's telling me it can't find the route.

I tried to make sure all my syntax is correct but I can't find the problem in my logic.

Error Message -

ActiveRecord::RecordNotFound at /orders/31/edit
Couldn't find Order with 'id'=31
file: core.rb location: find line: 155
BACKTRACE
(expand)
JUMP TO: GET POST COOKIES ENV
/Users/FutureChild/src/Crazy_Restaurant/controllers/orders_controller.rb in block in class:OrdersController
    @order = Order.find(params[:id])
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb in service
      si.service(req, res)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb in run
          server.service(req, res)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb in block in start_thread
          block ? block.call(sock) : run(sock)
GET

**Comment by eerlikh** [comment]
Andrew, can you possibly take a look at my issue? I want to finish this edit feature by today so I can implement the chef feature.

**Comment by amadden80** [comment]
_in person_
